<?php

/**
 * Implements hook_permission().
 */
function gsb_panels_ipe_overrides_permission() {
  return array(
    'administer panelizer defaults in ipe' => array(
      'title' => t('Administer panelizer defaults in In-Place Editor'),
      'description' => t('Allow users to save panelized pages as defaults.'),
    ),
  );
}

/**
 * Implements hook_panels_ipe_region_links_alter().
 */

/*
 * Commenting this out now. We are going to assume that the user will always be able to add 
 * some pane to the panelized page. In the future if that doesn't prove to be still the case
 * we can uncomment this code.
 *
 *
function gsb_panels_ipe_overrides_panels_ipe_region_links_alter(&$links, $context) {

  global $user;

  $create_perms = array();

  $create_perms[] = 'create fieldable accordion';
  $create_perms[] = 'create fieldable cta';
  $create_perms[] = 'create fieldable existing_node';
  $create_perms[] = 'create fieldable image_cta';
  $create_perms[] = 'create fieldable links';
  $create_perms[] = 'create fieldable people';
  $create_perms[] = 'create fieldable quote';
  $create_perms[] = 'create fieldable slideshow';
  $create_perms[] = 'create fieldable social_feed';
  $create_perms[] = 'create fieldable spotlight';
  $create_perms[] = 'create fieldable text';
  $create_perms[] = 'create fieldable video';

  foreach($create_perms as $key => $value) {
    if (user_access($value)) {
      return;
    }
  }

  unset($links['add-pane']);

}
*/

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gsb_panels_ipe_overrides_form_panels_ipe_edit_control_form_alter(&$form, &$form_state) {
  // Check if user has access to administer panelizer defaults, and if not
  // we just unset restricted actions.
  if (!user_access('administer panelizer defaults in ipe')) {
    $form['buttons']['submit']['#value'] = t('Save');
    if (isset($form['buttons']['save_default'])) {
      unset($form['buttons']['save_default']);
    }
    if (isset($form['buttons']['revert_default'])) {
      unset($form['buttons']['revert_default']);
    }
  };
}
