<?php

/**
 * Implements hook_panels_ipe_region_links_alter().
 */
function gsb_panels_ipe_overrides_panels_ipe_region_links_alter(&$links, $context) {

  global $user;

  $create_perms = array();

  $create_perms[] = 'create fieldable accordion';
  $create_perms[] = 'create fieldable cta';
  $create_perms[] = 'create fieldable existing_node';
  $create_perms[] = 'create fieldable image_cta';
  $create_perms[] = 'create fieldable links';
  $create_perms[] = 'create fieldable people';
  $create_perms[] = 'create fieldable quote';
  $create_perms[] = 'create fieldable slideshow';
  $create_perms[] = 'create fieldable social_feed';
  $create_perms[] = 'create fieldable spotlight';
  $create_perms[] = 'create fieldable text';
  $create_perms[] = 'create fieldable video';

  foreach($create_perms as $key => $value) {
    if (user_access($value)) {
      return;
    }
  }

  unset($links['add-pane']);
  
}


